apiVersion: v1
kind: Service
metadata:
  name: agri-food-api
  labels:
    app: agri-food-api
spec:
  selector:
    app: agri-food-api
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port }}
